version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=coopers_db
    depends_on:
      - mysql
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend


  websocket:
    build: ./websocket
    ports:
      - "3001:3001"

  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: coopers_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
